# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --legacy-peer-deps
    
    - name: run build
      run: npm run build
      env:
        CI: ""
    
    - name: build file upload to ec2
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PW }}
          port: 22
          source: "./dist"
          target: "/home/ec2-user/deploy/president"
#     - run: npm test
